### ISSUE TITLE
Docker 一键部署

### ISSUE THREAD

**Issue by ystemsrx** [FlypigGPT/Skin-care-system#1]
**不提PR了，随便改改**

Dockerfile

```
FROM node:18-alpine
RUN apk add --no-cache netcat-openbsd
WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com/

COPY package*.json ./
RUN npm install --production
COPY . .

RUN mkdir -p uploads
RUN chmod +x docker-entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./docker-entrypoint.sh"]

```

.dockerignore

```
node_modules
npm-debug.log
.git
.gitignore
README.md
.env
.nyc_output
coverage
.vscode
.DS_Store
*.log
```

docker-compose.yml

```yml
version: '3.8'

services:
  # 数据库
  mysql:
    image: mysql:8.0
    container_name: skincare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: skincare123
      MYSQL_DATABASE: skincare
      MYSQL_USER: skincare_user
      MYSQL_PASSWORD: skincare123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - skincare-network

  # Node.js应用
  app:
    build: .
    container_name: skincare-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=skincare123
      - DB_NAME=skincare
    networks:
      - skincare-network

volumes:
  mysql_data:

networks:
  skincare-network:
    driver: bridge
```

.env.example

```
# 数据库
DB_HOST=mysql
DB_USER=root
DB_PASSWORD=skincare123
DB_NAME=skincare

# 应用
NODE_ENV=production
PORT=3000

# MySQL
MYSQL_ROOT_PASSWORD=skincare123
MYSQL_DATABASE=skincare
MYSQL_USER=skincare_user
MYSQL_PASSWORD=skincare123
```

init.sql

```sql
-- 数据库
CREATE DATABASE IF NOT EXISTS skincare CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE skincare;

-- 用户
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  skin_type VARCHAR(20) DEFAULT '中性',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 皮肤记录
CREATE TABLE IF NOT EXISTS skin_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  record_date DATE NOT NULL,
  oil_level INT DEFAULT NULL,
  acne_level INT DEFAULT NULL,
  dryness_level INT DEFAULT NULL,
  photo_url VARCHAR(255) DEFAULT NULL,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 评论
CREATE TABLE IF NOT EXISTS comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  target_user_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (target_user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 回复
CREATE TABLE IF NOT EXISTS replies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  comment_id INT NOT NULL,
  user_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 点赞
CREATE TABLE IF NOT EXISTS likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  record_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_like (user_id, record_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (record_id) REFERENCES skin_records(id) ON DELETE CASCADE
);

-- 通知
CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  type VARCHAR(20) NOT NULL,
  from_user_id INT NOT NULL,
  record_id INT DEFAULT NULL,
  comment_id INT DEFAULT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (record_id) REFERENCES skin_records(id) ON DELETE CASCADE,
  FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);
```

docker-entrypoint.sh

```sh
#!/bin/sh
while ! nc -z mysql 3306; do
  sleep 1
done

node server.js
```

server.js 开头连数据库那里改为：

```js
const db = mysql.createConnection({
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || 'yan',
  database: process.env.DB_NAME || 'skincare'
});
```

结尾改为：

```js
app.listen(port, '0.0.0.0', () => {
  console.log(`服务器正在运行在 http://0.0.0.0:${port}`);
  console.log(`访问: http://localhost:${port} 使用`);
});
```

创建/修改上述文件后，根目录直接运行 `docker-compose up -d` 即可启动，在宿主机上访问 localhost:3000
